config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-cerulean-grasshopper.sh
        container: qc.acc_foggy-aquamarine-sponge
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-aqua-squirt.sh
        container: qc.doc_sleazy-orange-buzzard
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-fuchsia-tiger.sh
        container: qc.doc_crabby-smalt-anteater
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-green-armadillo.sh
        container: qc.doc_sleepy-champagne-peccary
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-fuchsia-avocet.sh
        container: qc.fair_shaggy-flax-dogfish
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-emerald-peccary.sh
        container: qc.lic_hilly-pink-giraffe
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-yellow-zebu.sh
        container: qc.ver_skanky-pink-skunk
timeout: 1800
