config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-apricot-markhor.sh
        container: qc.acc_homely-zucchini-frise
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-olivine-lizard.sh
        container: qc.doc_gloppy-thistle-bison
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-sapphire-harrier.sh
        container: qc.doc_foggy-seashell-gecko
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-mustard-mole.sh
        container: qc.doc_snippy-magenta-wildebeest
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-grey-wrasse.sh
        container: qc.lic_cloudy-carmine-ray
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-firebrick-weasel.sh
        container: qc.ver_skimpy-orchid-frise
timeout: 5400
