config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-linen-bulldog.sh
        container: qc.acc_breezy-wheat-spitz
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-ultramarine-tarsier.sh
        container: qc.doc_slaphappy-champagne-chihuahua
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-tangerine-warthog.sh
        container: qc.doc_messy-zucchini-armadillo
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-seashell-dhole.sh
        container: qc.doc_squeaky-cerulean-manatee
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-harlequin-mule.sh
        container: qc.lic_clammy-black-akita
  QC.Sty:
    repos:
      github.com/darce-i3m/testing stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-lime-ferret.sh
        container: qc.sty_ready-viridian-labradoodle
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-amber-wombat.sh
        container: qc.ver_ready-ivory-sloth
timeout: 5400
