config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-copper-dachsbracke.sh
        container: qc.acc_slaphappy-thistle-armadillo
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-brown-albatross.sh
        container: qc.doc_snippy-tomato-cat
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-sepia-cuttlefish.sh
        container: qc.doc_lumpy-tan-walrus
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-silver-bee.sh
        container: qc.doc_chewy-tomato-barracuda
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-olivine-angelfish.sh
        container: qc.lic_frumpy-smalt-budgerigar
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-pumpkin-grouse.sh
        container: qc.ver_shabby-azure-gerbil
timeout: 5400
