config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-smalt-echidna.sh
        container: qc.acc_stinky-ochre-schnauzer
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-plum-chow.sh
        container: qc.doc_paltry-xanthic-civet
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-cerulean-gar.sh
        container: qc.doc_queasy-coral-beetle
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-scarlet-raccoon.sh
        container: qc.doc_skanky-ivory-starfish
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-lavender-chimpanzee.sh
        container: qc.lic_sloppy-bronze-affenpinscher
  QC.Sty:
    repos:
      github.com/darce-i3m/testing stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-cinnabar-caiman.sh
        container: qc.sty_thirsty-blue-moth
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-lime-fly.sh
        container: qc.ver_tacky-chestnut-caracal
timeout: 5400
