config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-emerald-cow.sh
        container: qc.acc_pretty-bistre-hedgehog
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-ivory-schnauzer.sh
        container: qc.doc_gummy-smalt-mongrel
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-cobalt-mole.sh
        container: qc.doc_scaly-green-buzzard
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-peach-fox.sh
        container: qc.doc_freaky-turquoise-hornet
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-viridian-koala.sh
        container: qc.fair_thirsty-tomato-donkey
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-peach-dormouse.sh
        container: qc.lic_flabby-pink-ferret
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-viridian-audemer.sh
        container: qc.ver_skimpy-pumpkin-cichlid
timeout: 600
