config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-ochre-guppy.sh
        container: qc.acc_thirsty-denim-ladybird
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-indigo-burmese.sh
        container: qc.doc_skanky-cerulean-barnacle
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-lemon-husky.sh
        container: qc.doc_freaky-ruby-kiwi
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-cornflower-earwig.sh
        container: qc.doc_chummy-heliotrope-burmese
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-copper-cassowary.sh
        container: qc.fair_chewy-mustard-ladybird
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-orange-stingray.sh
        container: qc.lic_skanky-cornflower-kudu
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-cardinal-axolotl.sh
        container: qc.ver_cloudy-persimmon-bee
timeout: 1800
