config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-amethyst-horse.sh
        container: qc.acc_goopy-flax-lynx
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-green-chipmunk.sh
        container: qc.doc_thirsty-taupe-serval
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-puce-russel.sh
        container: qc.doc_silly-zucchini-capuchin
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-crimson-fly.sh
        container: qc.doc_cheeky-cerulean-spitz
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-jade-camel.sh
        container: qc.fair_bumpy-apricot-newt
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-chartreuse-oriole.sh
        container: qc.lic_wimpy-goldenrod-bongo
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-eggplant-whale.sh
        container: qc.ver_geeky-beige-birman
timeout: 1800
