config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-denim-squid.sh
        container: qc.acc_nippy-puce-rottweiler
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-magenta-balinese.sh
        container: qc.doc_hilly-myrtle-vole
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-taupe-rottweiler.sh
        container: qc.doc_bumpy-seashell-cichlid
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-alizarin-badger.sh
        container: qc.doc_chewy-cinnamon-hare
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-myrtle-paradise.sh
        container: qc.lic_seedy-puce-chipmunk
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-apricot-capybara.sh
        container: qc.ver_lousy-ivory-numbat
timeout: 1800
