config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-chartreuse-heron.sh
        container: qc.acc_grumpy-azure-cuttlefish
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-scarlet-impala.sh
        container: qc.doc_beady-persimmon-spaniel
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-russet-affenpinscher.sh
        container: qc.doc_messy-aqua-iguana
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-olivine-duck.sh
        container: qc.doc_bumpy-dandelion-capybara
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-pink-salamander.sh
        container: qc.fair_lumpy-yellow-caiman
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-sepia-armadillo.sh
        container: qc.lic_cheeky-brown-hummingbird
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-red-catfish.sh
        container: qc.ver_hazy-thistle-newfoundland
timeout: 1800
