config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-lavender-crocodile.sh
        container: qc.acc_freaky-cerise-rat
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-heliotrope-schnauzer.sh
        container: qc.doc_wheezy-aqua-barnacle
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-salmon-schnauzer.sh
        container: qc.doc_sloppy-chartreuse-devil
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-emerald-badger.sh
        container: qc.doc_pokey-celadon-cat
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-xanthic-goat.sh
        container: qc.fair_stinky-emerald-spitz
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-scarlet-affenpinscher.sh
        container: qc.lic_craggy-sepia-yak
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-flax-gerbil.sh
        container: qc.ver_blurry-eggplant-dachsbracke
timeout: 1800
