config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-taupe-octopus.sh
        container: qc.acc_wheezy-eggplant-dogfish
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-malachite-devil.sh
        container: qc.doc_chewy-cornflower-sponge
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-buff-hummingbird.sh
        container: qc.doc_clammy-silver-dane
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-jade-mule.sh
        container: qc.doc_shaggy-lemon-woodlouse
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-ochre-caterpillar.sh
        container: qc.lic_hazy-mauve-dachshund
  QC.Sty:
    repos:
      github.com/darce-i3m/testing stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-ruby-bird.sh
        container: qc.sty_hilly-celadon-olm
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-chocolate-goose.sh
        container: qc.ver_scaly-firebrick-quetzal
timeout: 5400
