config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-myrtle-kangaroo.sh
        container: qc.acc_woolly-celadon-chinchilla
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-green-elephant.sh
        container: qc.doc_messy-linen-wrasse
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-brown-retriever.sh
        container: qc.doc_freaky-persimmon-devil
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-ivory-tang.sh
        container: qc.doc_trippy-orange-nightingale
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-silver-mouse.sh
        container: qc.fair_chummy-fuchsia-impala
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-flax-catfish.sh
        container: qc.lic_sloppy-amber-wildebeest
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-lilac-buzzard.sh
        container: qc.ver_slimy-indigo-eagle
timeout: 600
