config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-pink-barb.sh
        container: qc.acc_gloppy-cinnamon-wallaby
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-black-quoll.sh
        container: qc.doc_wheezy-bronze-oyster
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-ecru-fossa.sh
        container: qc.doc_stealthy-amber-opossum
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-salmon-snake.sh
        container: qc.doc_snazzy-gold-lion
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-ecru-sparrow.sh
        container: qc.fair_boozy-firebrick-tetra
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-taupe-squirt.sh
        container: qc.lic_wimpy-copper-lizard
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-wisteria-lemur.sh
        container: qc.ver_stinky-carmine-jaguar
timeout: 1800
