config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-champagne-elephant.sh
        container: qc.acc_jumpy-lilac-wasp
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-blue-dollar.sh
        container: qc.doc_shaggy-thistle-bloodhound
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-vermilion-angora.sh
        container: qc.doc_hazy-charcoal-dragonfly
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-ivory-chipmunk.sh
        container: qc.doc_jumpy-thistle-whippet
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-orange-dormouse.sh
        container: qc.fair_snippy-eggplant-dogfish
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-pumpkin-lobster.sh
        container: qc.lic_woozy-salmon-cockroach
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-cinnabar-husky.sh
        container: qc.ver_seedy-olivine-bombay
timeout: 600
