config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-azure-opossum.sh
        container: qc.acc_slaphappy-chartreuse-millipede
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-firebrick-raccoon.sh
        container: qc.doc_lanky-emerald-robin
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-mauve-dolphin.sh
        container: qc.doc_breezy-saffron-loon
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-charcoal-badger.sh
        container: qc.doc_muzzy-khaki-spoonbill
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-firebrick-flamingo.sh
        container: qc.lic_greasy-tomato-akita
  QC.Sty:
    repos:
      github.com/darce-i3m/testing stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-grey-discus.sh
        container: qc.sty_paltry-asparagus-mayfly
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-myrtle-ladybird.sh
        container: qc.ver_whiny-ivory-vulture
timeout: 5400
