config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-heliotrope-chihuahua.sh
        container: qc.acc_shabby-salmon-dollar
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-auburn-wrasse.sh
        container: qc.doc_jumpy-cerise-weasel
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-emerald-mist.sh
        container: qc.doc_homely-carmine-manatee
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-gamboge-lizard.sh
        container: qc.doc_gummy-pear-duck
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-pumpkin-magpie.sh
        container: qc.fair_hazy-cornflower-orangutan
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-crimson-chameleon.sh
        container: qc.lic_flaky-white-gibbon
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-cerulean-tarsier.sh
        container: qc.ver_paltry-orchid-moorhen
timeout: 600
