config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-persimmon-warthog.sh
        container: qc.acc_tacky-charcoal-setter
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-coral-chinook.sh
        container: qc.doc_squeaky-violet-wallaby
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-viridian-chamois.sh
        container: qc.doc_fuzzy-lilac-cockroach
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-fuchsia-flamingo.sh
        container: qc.doc_silly-thistle-wasp
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-burgundy-hyena.sh
        container: qc.fair_squirrely-myrtle-crocodile
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-buff-foxhound.sh
        container: qc.lic_trippy-champagne-kudu
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-black-mist.sh
        container: qc.ver_lumpy-wheat-malamute
timeout: 1800
