config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-chartreuse-reindeer.sh
        container: qc.acc_seedy-viridian-hamster
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-beige-rottweiler.sh
        container: qc.doc_snoopy-tan-chicken
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-ecru-buffalo.sh
        container: qc.doc_leaky-ivory-insect
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-zucchini-leopard.sh
        container: qc.doc_woolly-cerulean-impala
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-bistre-gerbil.sh
        container: qc.lic_scanty-brass-shark
  QC.Sty:
    repos:
      github.com/darce-i3m/testing stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-bronze-flounder.sh
        container: qc.sty_thirsty-seashell-mule
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-peach-dingo.sh
        container: qc.ver_snippy-malachite-fox
timeout: 5400
