config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-puce-monkey.sh
        container: qc.acc_wimpy-plum-rabbit
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-amber-starfish.sh
        container: qc.doc_dorky-chestnut-squirrel
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cerise-bird.sh
        container: qc.doc_scummy-yellow-tiger
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-pear-donkey.sh
        container: qc.doc_stuffy-zucchini-drever
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-scarlet-bordeaux.sh
        container: qc.fair_hazy-olive-snail
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-gamboge-otter.sh
        container: qc.lic_baggy-salmon-ferret
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-ivory-hummingbird.sh
        container: qc.ver_baggy-rose-alligator
timeout: 600
