config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-xanthic-kakapo.sh
        container: qc.acc_scaly-blue-ibis
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-goldenrod-bat.sh
        container: qc.doc_surly-tangerine-coral
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-red-bonobo.sh
        container: qc.doc_boozy-rust-opossum
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-magnolia-fish.sh
        container: qc.doc_pokey-taupe-caterpillar
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-heliotrope-binturong.sh
        container: qc.fair_shabby-black-quokka
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-sepia-eleuth.sh
        container: qc.lic_lumpy-cardinal-frise
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-ivory-kakapo.sh
        container: qc.ver_muzzy-viridian-magpie
timeout: 1800
