config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cream-lemur.sh
        container: qc.acc_ready-ultramarine-dragonfly
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-ultramarine-crocodile.sh
        container: qc.doc_sleepy-ochre-moth
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-mauve-weasel.sh
        container: qc.doc_sleazy-auburn-seal
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-olivine-anteater.sh
        container: qc.doc_wimpy-ruby-audemer
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-champagne-dane.sh
        container: qc.lic_hilly-indigo-echidna
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-coral-buzzard.sh
        container: qc.ver_crappy-azure-jaguar
timeout: 1800
