config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/darce/testing:
      branch: main
      repo: https://gitlab.a.incd.pt/darce/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/darce/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-violet-rhinoceros.sh
        container: qc.acc_cozy-tangerine-fowl
  QC.Doc:
    repos:
      gitlab.a.incd.pt/darce/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-platinum-toucan.sh
        container: qc.doc_sloppy-turquoise-peccary
      gitlab.a.incd.pt/darce/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-thistle-goose.sh
        container: qc.doc_silly-pink-grasshopper
      gitlab.a.incd.pt/darce/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-carmine-spaniel.sh
        container: qc.doc_hilly-orange-yak
  QC.Lic:
    repos:
      gitlab.a.incd.pt/darce/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-brass-dolphin.sh
        container: qc.lic_squeaky-olive-millipede
  QC.Ver:
    repos:
      gitlab.a.incd.pt/darce/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-flax-hummingbird.sh
        container: qc.ver_snippy-cerulean-stingray
timeout: 5400
