config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-white-frigatebird.sh
        container: qc.acc_slimy-taupe-swan
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-orange-barnacle.sh
        container: qc.doc_clammy-crimson-sloth
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-beige-balinese.sh
        container: qc.doc_muggy-russet-malamute
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-taupe-cuscus.sh
        container: qc.doc_stuffy-jade-quoll
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-thistle-jaguar.sh
        container: qc.fair_silly-chestnut-ostrich
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-cardinal-chinchilla.sh
        container: qc.lic_ugly-pink-rattlesnake
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-flax-warthog.sh
        container: qc.ver_shaky-charcoal-bullfrog
timeout: 1800
