config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-bronze-shrimp.sh
        container: qc.acc_queasy-emerald-liger
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-maroon-cow.sh
        container: qc.doc_flaky-silver-lobster
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-corn-mau.sh
        container: qc.doc_blurry-olive-mongoose
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-auburn-scorpion.sh
        container: qc.doc_flabby-azure-chamois
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-pumpkin-tarsier.sh
        container: qc.fair_chewy-olivine-frise
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-wisteria-coati.sh
        container: qc.lic_skinny-xanthic-zorse
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-coral-albatross.sh
        container: qc.ver_ready-turquoise-caracal
timeout: 1800
