config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-plum-lobster.sh
        container: qc.acc_lanky-ruby-rottweiler
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-pumpkin-kakapo.sh
        container: qc.doc_sickly-seashell-weasel
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-blue-grouse.sh
        container: qc.doc_snippy-rose-kingfisher
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-beige-iguana.sh
        container: qc.doc_snoopy-lavender-birman
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-vermilion-albatross.sh
        container: qc.fair_snazzy-wheat-whippet
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-carmine-millipede.sh
        container: qc.lic_grumpy-dandelion-mole
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-xanthic-mau.sh
        container: qc.ver_skimpy-orange-angelfish
timeout: 1800
