config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-xanthic-dollar.sh
        container: qc.acc_sleepy-grey-jellyfish
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-seashell-shrimp.sh
        container: qc.doc_flabby-wheat-macaw
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-asparagus-squirt.sh
        container: qc.doc_goopy-blue-whale
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-aquamarine-zonkey.sh
        container: qc.doc_hazy-yellow-robin
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-purple-forest.sh
        container: qc.lic_whiny-lemon-magpie
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-carmine-ferret.sh
        container: qc.ver_sickly-saffron-indri
timeout: 1800
