config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-tomato-bongo.sh
        container: qc.acc_bluesy-alizarin-cichlid
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-bronze-swan.sh
        container: qc.doc_scanty-pink-drever
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-ivory-fish.sh
        container: qc.doc_scanty-rust-tuatara
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-platinum-tarantula.sh
        container: qc.doc_chummy-carmine-wolfhound
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-orchid-caracal.sh
        container: qc.lic_slaphappy-eggplant-kiwi
  QC.Sty:
    repos:
      github.com/darce-i3m/testing stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-cobalt-quail.sh
        container: qc.sty_geeky-champagne-macaw
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-pear-manatee.sh
        container: qc.ver_leaky-platinum-toad
timeout: 5400
