config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-persimmon-termite.sh
        container: qc.acc_hasty-taupe-cattle
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-silver-mole.sh
        container: qc.doc_wheezy-plum-nightingale
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-wheat-fousek.sh
        container: qc.doc_scanty-silver-coyote
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-scarlet-dragon.sh
        container: qc.doc_flabby-cyan-duck
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-flax-barb.sh
        container: qc.fair_dorky-cornflower-rattlesnake
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-saffron-weasel.sh
        container: qc.lic_trippy-coral-frog
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-aqua-moorhen.sh
        container: qc.ver_tacky-cinnamon-rattlesnake
timeout: 1800
