config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0-alpha2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-blue-vulture.sh
        container: qc.acc_fuzzy-zucchini-heron
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-ultramarine-dhole.sh
        container: qc.doc_freaky-lavender-rattlesnake
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-cerulean-terrier.sh
        container: qc.doc_stinky-khaki-tortoise
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-magenta-coati.sh
        container: qc.doc_stuffy-aquamarine-zebra
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-carmine-starfish.sh
        container: qc.fair_scanty-apricot-wolverine
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-aqua-turkey.sh
        container: qc.lic_homey-violet-ferret
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-platinum-catfish.sh
        container: qc.ver_sleepy-ultramarine-shrew
timeout: 1800
