config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-scarlet-ocelot.sh
        container: qc.acc_ugly-goldenrod-shrimp
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-tangerine-tang.sh
        container: qc.doc_messy-tomato-spitz
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-smalt-ostrich.sh
        container: qc.doc_hilly-asparagus-uguisu
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-celadon-bordeaux.sh
        container: qc.doc_sleepy-auburn-bullfrog
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-cinnabar-bee.sh
        container: qc.fair_wiggy-cardinal-mammoth
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-sepia-mammoth.sh
        container: qc.lic_snippy-scarlet-falcon
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-aquamarine-chinook.sh
        container: qc.ver_wimpy-pear-moose
timeout: 600
