config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-salmon-hyrax.sh
        container: qc.acc_cranky-dandelion-albatross
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-platinum-setter.sh
        container: qc.doc_trippy-emerald-millipede
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-russet-dunker.sh
        container: qc.doc_muggy-alizarin-bullfrog
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-maroon-alligator.sh
        container: qc.doc_scanty-goldenrod-pig
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-carmine-eel.sh
        container: qc.lic_smelly-charcoal-turkey
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-amaranth-mandrill.sh
        container: qc.ver_pokey-peach-crab
timeout: 5400
