config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-seashell-seahorse.sh
        container: qc.acc_goopy-denim-mist
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-purple-dugong.sh
        container: qc.doc_seedy-ultramarine-falcon
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-magnolia-snail.sh
        container: qc.doc_slaphappy-olive-jellyfish
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-green-uguisu.sh
        container: qc.doc_flabby-eggplant-coyote
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-fuchsia-mouse.sh
        container: qc.fair_fuzzy-vermilion-russel
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homely-violet-tarantula.sh
        container: qc.lic_droopy-firebrick-deer
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-cerulean-rat.sh
        container: qc.ver_boozy-periwinkle-mongrel
timeout: 600
