config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-coral-badger.sh
        container: qc.acc_jumpy-teal-echidna
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-cyan-tarsier.sh
        container: qc.doc_bumpy-mustard-saola
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-cerise-grasshopper.sh
        container: qc.doc_chewy-periwinkle-dog
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-bistre-chow.sh
        container: qc.doc_cloudy-coral-russel
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-goldenrod-reindeer.sh
        container: qc.fair_homey-green-greyhound
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-green-shark.sh
        container: qc.lic_flabby-bronze-gibbon
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-buff-bonobo.sh
        container: qc.ver_whiny-bistre-havanese
timeout: 600
