config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-orchid-frog.sh
        container: qc.acc_paltry-maroon-kudu
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-persimmon-centipede.sh
        container: qc.doc_muggy-gamboge-spaniel
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-pear-eel.sh
        container: qc.doc_lanky-amaranth-retriever
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-turquoise-budgerigar.sh
        container: qc.doc_sloppy-charcoal-starfish
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-chocolate-tzu.sh
        container: qc.lic_lanky-grey-scorpion
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-turquoise-nightingale.sh
        container: qc.ver_crabby-tangerine-fossa
timeout: 1800
