config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-cyan-dane.sh
        container: qc.acc_freaky-amber-audemer
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-olivine-woodlouse.sh
        container: qc.doc_bluesy-gold-sheep
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-scarlet-jackal.sh
        container: qc.doc_fuzzy-persimmon-saola
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-blue-paradise.sh
        container: qc.doc_snappy-vermilion-meerkat
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-razzmatazz-tang.sh
        container: qc.lic_cranky-silver-dhole
  QC.Sty:
    repos:
      github.com/darce-i3m/testing stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-brown-baboon.sh
        container: qc.sty_frumpy-sapphire-rabbit
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-buff-bonobo.sh
        container: qc.ver_hasty-purple-bulldog
timeout: 5400
