config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cinnamon-sparrow.sh
        container: qc.acc_crabby-cerulean-beetle
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-pear-cattle.sh
        container: qc.doc_scaly-rust-zorse
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-tomato-chimpanzee.sh
        container: qc.doc_thirsty-wheat-ray
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-harlequin-wasp.sh
        container: qc.doc_homely-cinnabar-dane
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-azure-guppy.sh
        container: qc.fair_scaly-chartreuse-flamingo
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-lime-schnauzer.sh
        container: qc.lic_skinny-flax-wasp
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-aquamarine-chihuahua.sh
        container: qc.ver_fuzzy-pumpkin-markhor
timeout: 600
