config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-dandelion-discus.sh
        container: qc.acc_queasy-cerulean-capybara
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-red-meerkat.sh
        container: qc.doc_bumpy-magnolia-sparrow
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-tan-cassowary.sh
        container: qc.doc_randy-black-mau
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-sapphire-dolphin.sh
        container: qc.doc_nippy-champagne-zorse
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-carmine-wolverine.sh
        container: qc.lic_craggy-bronze-hummingbird
  QC.Sty:
    repos:
      github.com/darce-i3m/testing stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-wheat-ferret.sh
        container: qc.sty_skimpy-champagne-russel
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-cinnamon-molly.sh
        container: qc.ver_skinny-teal-numbat
timeout: 5400
