config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-burgundy-frigatebird.sh
        container: qc.acc_randy-pumpkin-tang
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-emerald-anteater.sh
        container: qc.doc_muzzy-mustard-bongo
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-cinnamon-bordeaux.sh
        container: qc.doc_queasy-denim-tapir
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-thistle-cichlid.sh
        container: qc.doc_scaly-cardinal-tortoise
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-crimson-sparrow.sh
        container: qc.lic_cozy-chartreuse-sponge
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-amethyst-bird.sh
        container: qc.ver_gloppy-gold-cichlid
timeout: 5400
