config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-charcoal-audemer.sh
        container: qc.acc_ready-buff-monkey
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-white-wolf.sh
        container: qc.doc_hilly-zucchini-birman
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-smalt-terrier.sh
        container: qc.doc_tacky-taupe-vole
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-cerise-quail.sh
        container: qc.doc_sleazy-cerulean-sparrow
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-pear-dog.sh
        container: qc.fair_flaky-emerald-wolf
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-gold-liger.sh
        container: qc.lic_skimpy-zucchini-turtle
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-turquoise-eagle.sh
        container: qc.ver_chummy-persimmon-gibbon
timeout: 600
