config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/darce/testing:
      branch: main
      repo: https://gitlab.a.incd.pt/darce/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/darce/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-bistre-squirrel.sh
        container: qc.acc_lanky-charcoal-coati
  QC.Doc:
    repos:
      gitlab.a.incd.pt/darce/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-apricot-seahorse.sh
        container: qc.doc_lousy-brass-crab
      gitlab.a.incd.pt/darce/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-amaranth-dragonfly.sh
        container: qc.doc_sickly-chocolate-sloth
      gitlab.a.incd.pt/darce/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-aquamarine-bloodhound.sh
        container: qc.doc_snoopy-amber-kangaroo
  QC.Lic:
    repos:
      gitlab.a.incd.pt/darce/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-cream-anteater.sh
        container: qc.lic_pretty-smalt-dunker
  QC.Ver:
    repos:
      gitlab.a.incd.pt/darce/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-auburn-macaque.sh
        container: qc.ver_paltry-apricot-cockroach
timeout: 5400
