config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-smalt-pig.sh
        container: qc.acc_crabby-dandelion-mammoth
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-scarlet-albatross.sh
        container: qc.doc_randy-sangria-vole
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-persimmon-cat.sh
        container: qc.doc_cranky-persimmon-lion
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-smalt-discus.sh
        container: qc.doc_randy-jade-albatross
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-cornflower-dog.sh
        container: qc.fair_blurry-sapphire-schnauzer
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-emerald-coral.sh
        container: qc.lic_sloppy-chestnut-bonobo
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-eggplant-earwig.sh
        container: qc.ver_beady-brass-quoll
timeout: 1800
