config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-cream-armadillo.sh
        container: qc.acc_lousy-bistre-russel
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-puce-mist.sh
        container: qc.doc_scummy-dandelion-loon
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-smalt-mammoth.sh
        container: qc.doc_cloudy-beige-dogfish
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-amber-caterpillar.sh
        container: qc.doc_scaly-platinum-angora
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-lilac-cuscus.sh
        container: qc.fair_homely-coral-zebra
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-brown-hamster.sh
        container: qc.lic_tasty-chestnut-cow
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-platinum-forest.sh
        container: qc.ver_ready-indigo-ibis
timeout: 1800
