config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-denim-javanese.sh
        container: qc.acc_stealthy-magenta-dhole
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-tomato-orangutan.sh
        container: qc.doc_flaky-lilac-mouse
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-lavender-dalmatian.sh
        container: qc.doc_smelly-lemon-tamarin
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-bistre-quoll.sh
        container: qc.doc_nippy-coral-dalmatian
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-heliotrope-catfish.sh
        container: qc.lic_messy-cerulean-heron
  QC.Sty:
    repos:
      github.com/darce-i3m/testing stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-myrtle-mastiff.sh
        container: qc.sty_snazzy-blue-vulture
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-chartreuse-spitz.sh
        container: qc.ver_blurry-emerald-bird
timeout: 5400
