config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-flax-cat.sh
        container: qc.acc_nippy-asparagus-liger
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-denim-tang.sh
        container: qc.doc_hazy-lilac-scorpion
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-buff-shark.sh
        container: qc.doc_wimpy-copper-uguisu
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-turquoise-booby.sh
        container: qc.doc_stealthy-turquoise-scorpion
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-rose-kakapo.sh
        container: qc.fair_muggy-sangria-chihuahua
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-ochre-panda.sh
        container: qc.lic_shaky-lilac-bracke
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-charcoal-javanese.sh
        container: qc.ver_snoopy-cyan-walrus
timeout: 600
