config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-silver-capuchin.sh
        container: qc.acc_whiny-olivine-leopard
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-linen-bobcat.sh
        container: qc.doc_leaky-wisteria-skunk
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-linen-leopard.sh
        container: qc.doc_wheezy-periwinkle-woodlouse
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-violet-snail.sh
        container: qc.doc_lovely-emerald-bullfrog
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-indigo-tuatara.sh
        container: qc.lic_surly-purple-spitz
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-ivory-kangaroo.sh
        container: qc.ver_wimpy-puce-manatee
timeout: 5400
