config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-salmon-chinchilla.sh
        container: qc.acc_hilly-ochre-lemming
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-cardinal-quoll.sh
        container: qc.doc_geeky-goldenrod-tortoise
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-celadon-grouse.sh
        container: qc.doc_dorky-lavender-dachshund
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-chartreuse-opossum.sh
        container: qc.doc_queasy-cornflower-eel
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-gold-markhor.sh
        container: qc.lic_squeaky-peach-lizard
  QC.Sty:
    repos:
      github.com/darce-i3m/testing stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-apricot-quokka.sh
        container: qc.sty_squirrely-auburn-bat
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-plum-indri.sh
        container: qc.ver_crappy-ruby-tortoise
timeout: 5400
