config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-blue-donkey.sh
        container: qc.acc_muggy-red-akita
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-pear-neanderthal.sh
        container: qc.doc_wheezy-amaranth-gibbon
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-zucchini-axolotl.sh
        container: qc.doc_craggy-sangria-koala
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-cerise-giraffe.sh
        container: qc.doc_greasy-brass-albatross
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-persimmon-monkey.sh
        container: qc.lic_baggy-brass-donkey
  QC.Sty:
    repos:
      github.com/darce-i3m/testing stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-turquoise-clam.sh
        container: qc.sty_scummy-ecru-deer
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-chartreuse-husky.sh
        container: qc.ver_hasty-olivine-koala
timeout: 5400
