config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-beige-giraffe.sh
        container: qc.acc_ready-chartreuse-barb
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-black-tiger.sh
        container: qc.doc_sleazy-scarlet-frise
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-buff-barb.sh
        container: qc.doc_tasty-red-flounder
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-sapphire-sheep.sh
        container: qc.doc_grumpy-plum-bear
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-indigo-swan.sh
        container: qc.lic_snappy-zucchini-oyster
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-bistre-devil.sh
        container: qc.ver_beady-goldenrod-husky
timeout: 1800
