config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-denim-birman.sh
        container: qc.acc_craggy-cinnabar-hamster
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-taupe-avocet.sh
        container: qc.doc_hilly-xanthic-loon
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-turquoise-mongoose.sh
        container: qc.doc_blurry-persimmon-budgerigar
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-puce-panda.sh
        container: qc.doc_randy-goldenrod-opossum
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-amaranth-angora.sh
        container: qc.lic_silly-cardinal-tarsier
  QC.Sty:
    repos:
      github.com/darce-i3m/testing stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-cerise-lemming.sh
        container: qc.sty_hazy-cardinal-bonobo
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-tangerine-quokka.sh
        container: qc.ver_ugly-bronze-walrus
timeout: 5400
