config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-malachite-zebu.sh
        container: qc.acc_craggy-sapphire-tuatara
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-red-kangaroo.sh
        container: qc.doc_queasy-champagne-mule
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-puce-magpie.sh
        container: qc.doc_tasty-vermilion-moorhen
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-scarlet-quoll.sh
        container: qc.doc_sleazy-zucchini-whippet
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-gold-llama.sh
        container: qc.lic_lovely-khaki-newfoundland
  QC.Sty:
    repos:
      github.com/darce-i3m/testing stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-olive-shrew.sh
        container: qc.sty_skimpy-rust-flamingo
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-viridian-seahorse.sh
        container: qc.ver_freaky-purple-lion
timeout: 5400
