config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-orange-eagle.sh
        container: qc.acc_craggy-blue-kangaroo
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-wheat-albatross.sh
        container: qc.doc_leaky-tan-chipmunk
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-zucchini-capuchin.sh
        container: qc.doc_cheeky-tan-balinese
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-burgundy-lizard.sh
        container: qc.doc_skanky-turquoise-snail
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-champagne-labradoodle.sh
        container: qc.fair_silly-burgundy-chinook
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-viridian-slug.sh
        container: qc.lic_sunny-rust-vole
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-lilac-cockroach.sh
        container: qc.ver_flabby-ruby-dunker
timeout: 600
