config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-plum-kangaroo.sh
        container: qc.acc_leaky-copper-cattle
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-tomato-grouse.sh
        container: qc.doc_tacky-maroon-toad
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-amethyst-booby.sh
        container: qc.doc_crappy-zucchini-squirrel
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-rust-guppy.sh
        container: qc.doc_frumpy-xanthic-tiger
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-taupe-chipmunk.sh
        container: qc.fair_snazzy-cerise-javanese
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-apricot-falcon.sh
        container: qc.lic_squirrely-lavender-clam
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-olivine-malamute.sh
        container: qc.ver_shabby-turquoise-chin
timeout: 1800
