config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-lime-goose.sh
        container: qc.acc_wimpy-periwinkle-lizard
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-mauve-dingo.sh
        container: qc.doc_flimsy-thistle-kangaroo
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-razzmatazz-dalmatian.sh
        container: qc.doc_crappy-heliotrope-loon
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-apricot-capybara.sh
        container: qc.doc_hazy-lilac-otter
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-chestnut-javanese.sh
        container: qc.lic_cheeky-persimmon-dog
  QC.Sty:
    repos:
      github.com/darce-i3m/testing stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-black-insect.sh
        container: qc.sty_skanky-red-fossa
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-khaki-llama.sh
        container: qc.ver_slimy-turquoise-wombat
timeout: 5400
