config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-denim-swan.sh
        container: qc.acc_queasy-chocolate-otter
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-cyan-coyote.sh
        container: qc.doc_messy-taupe-neanderthal
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-puce-tamarin.sh
        container: qc.doc_randy-jade-malamute
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-celadon-lobster.sh
        container: qc.doc_silly-platinum-oriole
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-grey-duck.sh
        container: qc.fair_cloudy-asparagus-barracuda
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-cerulean-havanese.sh
        container: qc.lic_cozy-scarlet-seahorse
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-goldenrod-lobster.sh
        container: qc.ver_jumpy-tomato-wildebeest
timeout: 1800
