config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/darce/testing:
      branch: main
      repo: https://gitlab.a.incd.pt/darce/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/darce/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-firebrick-boar.sh
        container: qc.acc_scanty-mauve-gharial
  QC.Doc:
    repos:
      gitlab.a.incd.pt/darce/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-smalt-moose.sh
        container: qc.doc_hasty-white-yak
      gitlab.a.incd.pt/darce/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-brown-tamarin.sh
        container: qc.doc_gamy-turquoise-mongoose
      gitlab.a.incd.pt/darce/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-maroon-crab.sh
        container: qc.doc_cheeky-aquamarine-javanese
  QC.Lic:
    repos:
      gitlab.a.incd.pt/darce/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-razzmatazz-dingo.sh
        container: qc.lic_blurry-razzmatazz-burmese
  QC.Ver:
    repos:
      gitlab.a.incd.pt/darce/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-sepia-fossa.sh
        container: qc.ver_nippy-tangerine-greyhound
timeout: 5400
