config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-silver-fousek.sh
        container: qc.acc_ready-lavender-raccoon
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-azure-yak.sh
        container: qc.doc_crappy-lilac-forest
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-seashell-bullfrog.sh
        container: qc.doc_boozy-lemon-newt
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-periwinkle-slug.sh
        container: qc.doc_skinny-coral-seahorse
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-sepia-corgi.sh
        container: qc.lic_boozy-malachite-tuatara
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-beige-sloth.sh
        container: qc.ver_paltry-seashell-flamingo
timeout: 5400
