config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/darce-i3m/testing:
      branch: main
      repo: https://github.com/darce-i3m/testing
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-green-snail.sh
        container: qc.acc_flimsy-mustard-lemming
  QC.Doc:
    repos:
      github.com/darce-i3m/testing find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-sapphire-frog.sh
        container: qc.doc_slimy-heliotrope-lemming
      github.com/darce-i3m/testing git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-carmine-devil.sh
        container: qc.doc_thirsty-denim-tarsier
      github.com/darce-i3m/testing markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-emerald-urchin.sh
        container: qc.doc_stinky-cinnabar-walrus
  QC.FAIR:
    repos:
      github.com/darce-i3m/testing F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-yellow-dragon.sh
        container: qc.fair_smelly-salmon-liger
  QC.Lic:
    repos:
      github.com/darce-i3m/testing licensee:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-periwinkle-tuatara.sh
        container: qc.lic_cheeky-razzmatazz-jellyfish
  QC.Ver:
    repos:
      github.com/darce-i3m/testing get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-taupe-caiman.sh
        container: qc.ver_boozy-magnolia-paradise
timeout: 600
